// Nederlandse namen voor landen zoals de databron (ESPN) ze in het Engels teruggeeft.
// Ook tegenstanders van buiten Europa staan erin, voor de vriendschappelijke duels en het WK.
// Onbekende namen worden ongewijzigd getoond.
window.LANDEN_NL = {
  // Europa (UEFA)
  'Albania': 'Albanië',
  'Andorra': 'Andorra',
  'Armenia': 'Armenië',
  'Austria': 'Oostenrijk',
  'Azerbaijan': 'Azerbeidzjan',
  'Belarus': 'Wit-Rusland',
  'Belgium': 'België',
  'Bosnia and Herzegovina': 'Bosnië en Herzegovina',
  'Bosnia & Herzegovina': 'Bosnië en Herzegovina',
  'Bosnia': 'Bosnië en Herzegovina',
  'Bosnia-Herzegovina': 'Bosnië en Herzegovina',
  'Bulgaria': 'Bulgarije',
  'Croatia': 'Kroatië',
  'Cyprus': 'Cyprus',
  'Czech Republic': 'Tsjechië',
  'Czechia': 'Tsjechië',
  'Denmark': 'Denemarken',
  'England': 'Engeland',
  'Estonia': 'Estland',
  'Faroe Islands': 'Faeröer',
  'Finland': 'Finland',
  'France': 'Frankrijk',
  'Georgia': 'Georgië',
  'Germany': 'Duitsland',
  'Gibraltar': 'Gibraltar',
  'Greece': 'Griekenland',
  'Hungary': 'Hongarije',
  'Iceland': 'IJsland',
  'Ireland': 'Ierland',
  'Republic of Ireland': 'Ierland',
  'Israel': 'Israël',
  'Italy': 'Italië',
  'Kazakhstan': 'Kazachstan',
  'Kosovo': 'Kosovo',
  'Latvia': 'Letland',
  'Liechtenstein': 'Liechtenstein',
  'Lithuania': 'Litouwen',
  'Luxembourg': 'Luxemburg',
  'Malta': 'Malta',
  'Moldova': 'Moldavië',
  'Montenegro': 'Montenegro',
  'Netherlands': 'Nederland',
  'North Macedonia': 'Noord-Macedonië',
  'FYR Macedonia': 'Noord-Macedonië',
  'Macedonia': 'Noord-Macedonië',
  'Northern Ireland': 'Noord-Ierland',
  'Norway': 'Noorwegen',
  'Poland': 'Polen',
  'Portugal': 'Portugal',
  'Romania': 'Roemenië',
  'Russia': 'Rusland',
  'San Marino': 'San Marino',
  'Scotland': 'Schotland',
  'Serbia': 'Servië',
  'Slovakia': 'Slowakije',
  'Slovenia': 'Slovenië',
  'Spain': 'Spanje',
  'Sweden': 'Zweden',
  'Switzerland': 'Zwitserland',
  'Turkey': 'Turkije',
  'Türkiye': 'Turkije',
  'Turkiye': 'Turkije',
  'Ukraine': 'Oekraïne',
  'Wales': 'Wales',

  // Zuid-Amerika
  'Argentina': 'Argentinië',
  'Bolivia': 'Bolivia',
  'Brazil': 'Brazilië',
  'Chile': 'Chili',
  'Colombia': 'Colombia',
  'Ecuador': 'Ecuador',
  'Paraguay': 'Paraguay',
  'Peru': 'Peru',
  'Uruguay': 'Uruguay',
  'Venezuela': 'Venezuela',

  // Noord- en Midden-Amerika, Caribisch gebied
  'USA': 'Verenigde Staten',
  'United States': 'Verenigde Staten',
  'Canada': 'Canada',
  'Mexico': 'Mexico',
  'Costa Rica': 'Costa Rica',
  'Panama': 'Panama',
  'Honduras': 'Honduras',
  'El Salvador': 'El Salvador',
  'Guatemala': 'Guatemala',
  'Jamaica': 'Jamaica',
  'Haiti': 'Haïti',
  'Trinidad and Tobago': 'Trinidad en Tobago',
  'Curacao': 'Curaçao',
  'Curaçao': 'Curaçao',
  'Suriname': 'Suriname',

  // Afrika
  'Algeria': 'Algerije',
  'Angola': 'Angola',
  'Burkina Faso': 'Burkina Faso',
  'Cameroon': 'Kameroen',
  'Cape Verde': 'Kaapverdië',
  'Cape Verde Islands': 'Kaapverdië',
  'Congo': 'Congo-Brazzaville',
  'Congo DR': 'DR Congo',
  'Congo DR (Zaire)': 'DR Congo',
  'DR Congo': 'DR Congo',
  'Egypt': 'Egypte',
  'Equatorial Guinea': 'Equatoriaal-Guinea',
  'Gabon': 'Gabon',
  'Gambia': 'Gambia',
  'Ghana': 'Ghana',
  'Guinea': 'Guinee',
  'Ivory Coast': 'Ivoorkust',
  "Côte d'Ivoire": 'Ivoorkust',
  'Kenya': 'Kenia',
  'Mali': 'Mali',
  'Morocco': 'Marokko',
  'Nigeria': 'Nigeria',
  'Senegal': 'Senegal',
  'South Africa': 'Zuid-Afrika',
  'Tunisia': 'Tunesië',
  'Zambia': 'Zambia',

  // Azië en Oceanië
  'Australia': 'Australië',
  'China': 'China',
  'China PR': 'China',
  'India': 'India',
  'Indonesia': 'Indonesië',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Japan': 'Japan',
  'Jordan': 'Jordanië',
  'Korea Republic': 'Zuid-Korea',
  'Republic of Korea': 'Zuid-Korea',
  'South Korea': 'Zuid-Korea',
  'North Korea': 'Noord-Korea',
  'New Zealand': 'Nieuw-Zeeland',
  'Oman': 'Oman',
  'Qatar': 'Qatar',
  'Saudi Arabia': 'Saoedi-Arabië',
  'Syria': 'Syrië',
  'Thailand': 'Thailand',
  'United Arab Emirates': 'Verenigde Arabische Emiraten',
  'Uzbekistan': 'Oezbekistan',
  'Vietnam': 'Vietnam',
};

// Competitienamen in het Nederlands (het script levert ze meestal al in het Nederlands aan).
window.COMPETITIES_NL = {
  'Friendlies': 'Vriendschappelijk',
  'UEFA Nations League': 'Nations League',
  'World Cup': 'WK',
  'World Cup - Qualification Europe': 'WK-kwalificatie',
  'Euro Championship': 'EK',
  'Euro Championship - Qualification': 'EK-kwalificatie',
};
